### ISSUE TITLE
Requirements prevent library imoport on DB 7.3+

### ISSUE THREAD

**Issue by mprojlb** [Labelbox/labelspark#19]
The setup.py requirements prevent the library from running on Azure Databricks 7.3+

The requirements in setup.py include pyspark, databricks and koalas. These packages are installed by default on Databricks. When running `%pip install labelspark` with the current setup it will install a different version of pyspark, databricks and koalas from Pypi. The package called databricks on Pypi is not the correct package and will overwrite the proper package on Databricks. This will cause `import labelspark` to fail with the error:

> ModuleNotFoundError: No module named 'databricks.koalas' 

A simple fix is to remove pyspark, databricks and koalas from the requirements.

**Comment by mprojlb** [comment]
#20

**Comment by nickaustinlee** [comment]
Merged and pushed as v0.2.1 -thanks for the contribution!
