### ISSUE TITLE
New Bug: 0.5.2

### ISSUE THREAD

**Issue by avn3r** [Labelbox/labelspark#45]
https://github.com/Labelbox/labelspark/blob/27ead6b2ce5c2d37794c38d76f267045d06eea72/labelspark/bronze_to_silver.py#L27

variable `needs_koalas` doesn't exist in `bronze_to_silver` since you commented out the variable creation part!

**Comment by nickaustinlee** [comment]
Hi @avn3r thanks for reporting this. I'll submit a PR which should fix this.
